USE customer_behaviour
-- Test query to refer the database which will help solving other querries
select top 10 * 
from Customer;


--Q1. What is the total revenue generated by male vs. female customers?
SELECT gender, FORMAT(SUM(purchase_amount),'C','en-US') AS revenue
FROM Customer
GROUP BY gender

UNION ALL

SELECT 'Total', FORMAT(SUM(purchase_amount),'C','en-US')
FROM Customer;


--Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT customer_id, purchase_amount 
FROM Customer
WHERE discount_applied = 'Yes' and purchase_amount >=(SELECT AVG(purchase_amount) FROM Customer);


-- Q3. Which are the top 5 products with the highest average review rating?
SELECT TOP 5 item_purchased, ROUND (AVG(review_rating),2) AS avg_rating
FROM Customer
GROUP BY item_purchased
ORDER BY avg_rating DESC;


--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
SELECT shipping_type, ROUND(AVG(purchase_amount),2) AS avg_purchase_amount
FROM Customer
WHERE shipping_type in ('Express','Standard')
GROUP BY shipping_type


--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
SELECT  
    subscription_status, 
    COUNT(customer_id), 
    AVG(purchase_amount) AS avg_spend, 
    SUM(purchase_amount) AS total_revenue
FROM Customer
GROUP BY subscription_status


--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT TOP 5 item_purchased,ROUND(100.0 * SUM(CASE WHEN discount_applied='Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM Customer
GROUP BY item_purchased
ORDER BY discount_rate DESC


--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
-- Step 1: Create a Common Table Expression (CTE) to segment customers
WITH customer_type AS (
    SELECT customer_id, previous_purchases,
    CASE
        WHEN previous_purchases = 1 THEN 'New'
        WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
        ELSE 'Loyal'END AS customer_segment
    FROM Customer)
-- Step 2: Aggregate the number of customers in each segment
SELECT customer_segment,count(*) AS number_of_customers
FROM customer_type
GROUP BY customer_segment
ORDER BY number_of_customers;


--Q8. What are the top 3 most purchased products within each category? 
-- Step 1: Aggregate the total number of orders per product in each category
WITH item_counts as(
    SELECT item_purchased, category, count(*) AS total_purchased
    FROM Customer
    GROUP BY category, item_purchased
),
-- Step 2: Rank products within each category based on total orders
ranked_items as (
    SELECT *,
    DENSE_RANK() OVER(
    PARTITION BY category                   -- Reset ranking for each category
    ORDER BY total_purchased DESC           -- Rank products by descending order count
    ) AS item_rank                          -- Assign rank, same total_purchased get same rank
    FROM item_counts
)
-- Step 3: Select only the top 3 products in each category
SELECT *
FROM ranked_items
WHERE item_rank <= 3;

 
--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status, COUNT(*) AS repeat_buyers
FROM Customer
WHERE previous_purchases > 5
GROUP BY subscription_status;


--Q10. What is the revenue contribution of each age group? 
SELECT age_group,SUM(purchase_amount) AS total_revenue
FROM Customer
GROUP BY age_group
ORDER BY total_revenue DESC;